### ISSUE TITLE
Search Bar not working for tags

### ISSUE THREAD

**Issue by thisispav** [pubky/pubky-beta#376] opened 2024-08-09 10:13 UTC
for some reason I can't search for any tags even though I just tagged a post (with tag pubky)

<img width="926" alt="Search not working" src="https://github.com/user-attachments/assets/b8e8e8f2-85f7-4bdf-99cf-1e321e81851a">

**Comment by catch-21** [comment] 2024-08-09 10:26
Same for me, even when searching for a tag that I can see with my current filter.

**Comment by catch-21** [comment] 2024-08-09 16:45
I think this is not a bug. This behaviour is due to the filter being for "Friends" and the posts with this tag are only shown when using "All". I'm closing this now. @thisispav please reopen if I am misunderstood.

**Closed as completed by catch-21** 2024-08-09 16:45 UTC
