### ISSUE TITLE
Notification Time Stamp

### ISSUE THREAD

**Issue by thisispav** [pubky/pubky-beta#372] opened 2024-08-09 09:22 UTC
for some reason testing with JC and James when I followed them both I get different (wrong) timestamp notifications - please refer to image. 

<img width="613" alt="time stamp error" src="https://github.com/user-attachments/assets/deddc089-2e00-44d7-949a-9fe81db92f1a">

**Comment by catch-21** [comment] 2024-08-09 09:29
It looks like the most recent notifications is sometimes using unix time 0 here.
Unix time 0 is 1st Jan 1970, which is 54 years 7 months ago.
The backend shouldn't serve up data unless it has the correct time.

**Comment by thisispav** [comment] 2024-08-09 09:39
Upon relogging to the account, I can now see that the time stamps appear to be showing the correct time for all the notifications. I did a speed test and it is OK. App is still quite slow for me, maybe because I am using a VPN?

**Comment by catch-21** [comment] 2024-08-16 09:18
Today we noticed that @thisispav's PC has a local time that is behind by ~5 minutes. This is likely the cause of this.

**Comment by flaviomoceri** [comment] 2024-08-28 13:04
I can't replicate the error, if it's still there, can you explain to me how to replicate it please? 🙏

**Comment by catch-21** [comment] 2024-08-28 16:51
Set your local clock back 5 minutes 😂 
No, I don't think this is bug. Closing.

**Closed as completed by catch-21** 2024-08-28 16:51 UTC
Labels: bug
